//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_AlyusevaSofyaViktorovna.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.Stats = new HashSet<Stats>();
        }
    
        public int IdMatch { get; set; }
        public Nullable<System.DateTime> DateTimeStart { get; set; }
        public Nullable<System.TimeSpan> TimeLasted { get; set; }
        public Nullable<int> IdTournament { get; set; }
        public Nullable<int> IdFirstPlayer { get; set; }
        public Nullable<int> IsSecPlayer { get; set; }
        public Nullable<int> FirstPlayerScore { get; set; }
        public Nullable<int> SecPlayerScore { get; set; }
    
        public virtual Tournaments Tournaments { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stats> Stats { get; set; }
    }
}
