//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_AlyusevaSofyaViktorovna.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stats
    {
        public int IdStat { get; set; }
        public Nullable<int> KillAmount { get; set; }
        public Nullable<int> IdMatch { get; set; }
        public Nullable<int> IdUser { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Users Users { get; set; }
    }
}
